name: Deploy Key Pair to Bastion Server

on:
  workflow_dispatch:

jobs:
  setup-bastion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key and Connect to Server
        uses: appleboy/ssh-action@v1.0.3
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: EC2_SSH_KEY
          script: |
            # ১. SSH ডিরেক্টরি তৈরি (যদি না থাকে)
            if [ ! -d ~/.ssh ]; then
              mkdir -p ~/.ssh
              chmod 700 ~/.ssh
              echo "SSH directory created successfully."
            else
              echo "SSH directory already exists."
            fi

            # ২. প্রাইভেট কি (Private Key) ফাইল তৈরি
            KEY_FILE=~/.ssh/abd_bs_ubuntu.pem
            if [ ! -f "$KEY_FILE" ]; then
              echo "$EC2_SSH_KEY" > "$KEY_FILE"
              chmod 600 "$KEY_FILE"
              echo "Key pair file created successfully!"
            else
              echo "Key pair already exists."
            fi